compile btn logic
ruffed/r pull request #1
Opened 2024-03-17 19:17 UTC by alisya-k

- added POST form and event handler to reach /compile in backend

2024-03-17 19:32 UTC, aidenfoxivey commented on lombardy/templates/index.html
> +    <form action="/compile" method="post" id="compileForm">
Is a form necessary if you're reading off the DOM?

Should be able to do an event listener 
`document.getElementById("myBtn").addEventListener("click", displayDate);` that just takes the current value

editor.getValue()

and then writes a POST through `fetch` to the backend with the data

2024-03-17 19:32 UTC, aidenfoxivey commented on lombardy/src/main.go
> +		c.HTML(http.StatusOK, "index.html", gin.H{
why is compile returning index.html

2024-03-17 19:39 UTC, aidenfoxivey commented
Thoughts on a refactor that removes the Post form and does some JS instead?

2024-03-17 19:50 UTC, alisya-k commented on lombardy/templates/index.html
> +    <form action="/compile" method="post" id="compileForm">
I agree I actually forgot that existed

2024-03-17 19:52 UTC, alisya-k commented on lombardy/src/main.go
> +		c.HTML(http.StatusOK, "index.html", gin.H{
It should redirect to it with data, I did not know how to do that lol

2024-03-18 04:33 UTC, aidenfoxivey commented on lombardy/src/main.go
> +	// "os/exec"
If you need to remove this, then probably just remove this - otherwise uncomment

2024-03-18 04:33 UTC, aidenfoxivey commented on lombardy/src/main.go
> +		// cmd := exec.Command("cc", "main.c")
Why are we commenting this out here?

2024-03-18 04:34 UTC, aidenfoxivey requested changes

2024-03-18 04:34 UTC, aidenfoxivey commented on lombardy/src/main.go
> +		c.JSON(http.StatusOK, gin.H{"res": src.Source})
I take it this is just echoing then.

2024-03-18 21:28 UTC, alisya-k commented on lombardy/src/main.go
> +		c.JSON(http.StatusOK, gin.H{"res": src.Source})
yes it is a lovely poc

2024-03-18 21:31 UTC, alisya-k commented on lombardy/src/main.go
> +	// "os/exec"
it's removed in the cosmic sense

2024-03-18 23:56 UTC, aidenfoxivey approved these changes

2024-03-18 23:56 UTC, merged